### ISSUE TITLE
Highstock component example not working

### ISSUE THREAD

**Issue by aaronrosenthal** [richardeschloss/nuxt-highcharts#46]
### Version
nuxt-highcharts: 3.0.2 
nuxt3: 3.0.0-27468803.23e7afb 
highcharts: 10.0.0

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration for nuxt-highcharts

```
export default defineNuxtConfig({
  modules: ["nuxt-highcharts"]
});
```

### Reproduction Link

https://codesandbox.io/s/priceless-sanne-3ccmhg?file=/nuxt.config.ts

### Steps to reproduce

Minimal setup with Nuxt3 and the provided Highstock example.

### What is Expected?

Example should work.

### What is actually happening?

The stockChart does not ever render. The following error is thrown (can be seen in the dev tools console):

```
Uncaught (in promise) TypeError: SeriesRegistry is undefined
    NuxtJS 5
        <anonymous>
        _registerModule
        <anonymous>
        <anonymous>
        <anonymous>
[indicators-all.src.js:39:22](https://3ccmhg.sse.codesandbox.io/_nuxt/node_modules/nuxt-highcharts/node_modules/highcharts/indicators/indicators-all.src.js?v=ed8cceaf)
```

It appears the line of code that is causing the issue is here: https://github.com/richardeschloss/nuxt-highcharts/blob/feat/v3/lib/components.js#L34

However I'm not sure if this is a nuxt-highcharts issue or if its a Highcharts issue. I did also try with Highcharts version 9.3.0 (instead of 10.0.0) but that did not fix the problem.

**Comment by richardeschloss** [comment]
Hi, https://github.com/richardeschloss/nuxt-highcharts/tree/feat/v3 contains the working stockChart example (and just re-tested). It's currently tested against Highcharts 9.x. There are plans to make it compatible with Highcharts 10.x (released 18 days ago). 

nuxt-highcharts lists "highcharts 9.x" as a dependency, so installing just "nuxt-highcharts@next" should install the compatible version of highcharts. You may have to remove package-lock.json and node_modules before installing to get the dependencies fixed.

**Comment by richardeschloss** [comment]
https://github.com/richardeschloss/nuxt-highcharts/tree/feat/v3-hc10 pushed and tested against highcharts v10. Highstock works.

**Comment by aaronrosenthal** [comment]
I'm not sure what I'm doing wrong, I updated my codesandbox so it only installs nuxt-highcharts@next and doesn't have Highcharts as a dependency, but it's still throwing the same error. Is it a Nuxt3 issue?

**Comment by richardeschloss** [comment]
According to the console output in that particular codesandbox, there is an unhandled error exception occurring in the pages/index.vue mounted hook. It appears as though, while in the codesandbox environment, there is an error fetching the "ohlcv.json" data resulting in empty series data (and no chart). 

From the console output:
"[Vue warn]: Unhandled error during execution of mounted hook 
  at <Highstock options= 
{chart: Object, rangeSelector: Object, title: Object, series: Array(0)}
"

I'm able to run your exact code locally and get it to work. I'm guessing to get it to work right in codesandbox, you may want to try fetching the full url https://3ccmhg.sse.codesandbox.io/ohlcv.json

**Comment by g-tejas** [comment]
Hi, im facing the same issue, and im unable to fix the error even using the full url, I can see in the Vue developer extension that the data is correctliny being fetched, but im not sure why its not displaying

**Comment by richardeschloss** [comment]
@g-tejas can you please share your most recent code sandbox?

**Comment by g-tejas** [comment]
I have copy pasted the code from the sandbox provided in the earlier comments, into my local project. Its not working on my local project, with/without the full URL. I think the only different would be the dependencies and how they were installed. May i confirm how i can go about installing nuxt-highcharts properly for the latest 3.0.3 version? I deleted the lockfiles, node_modules, and reinstalled (without explicity stating main highcharts) since you said that highcharts is a dependency of nuxt-highcharts, and it will auto install. I am using nuxt 3.0.0 rc3.

**Comment by richardeschloss** [comment]
Hi, nuxt 3 *rc* introduced (breaking changes)[https://github.com/nuxt/framework/discussions/2883]) that this module has not yet accounted for. The main change breaking the code is the naming convention change for the runtime config.  It's on my roadmap to support that version as soon as I can but will be delayed by other financial / work obligations I have. However, I'm not sure how much I should do just yet because the nuxt3 project is iterating much faster (and it's possible that whatever changes I make to support the rc version today will work one day but not another).

For the time being though, nuxt3 at 3.0.0-27365391.7479eac works with this library:
> npm i nuxt3@3.0.0-27365391.7479eac

Cloning this git repo and switching the known working branch feat/v3 can also be helpful.

**Comment by g-tejas** [comment]
Thank you for your help! I'll try your solution of changing the nuxt version to the one mentioned. Also, i see from the nuxt official roadmap that, stable version of nuxt3 will be out in june, which is not too far away. So i guess that would be the endpoint? Either ways, i really appreciate you doing this, and making this amazing plugin, thanks alot.

**Comment by richardeschloss** [comment]
My goal is to get the support before they roll out the stable version in June.

**Comment by richardeschloss** [comment]
Released support for nuxt3rc version: 
> npm i nuxt-socket-io@nuxt3rc

Tested against highcharts **10.0.0.**

**Comment by g-tejas** [comment]
Thank you!!  I have a small problem, whenever I install nuxt-highcharts@3.0.4, its installing highcharts 10.1.0 instead of 10.0.0. Should i just manually specify it in package.json and yarn install it? Also whats the difference. between rc3 and the one shown below (i cloned your branch)
<img width="420" alt="Screenshot 2022-05-23 at 4 18 51 PM" src="https://user-images.githubusercontent.com/76802638/169775519-4d5ff983-a20d-4df4-8dff-082c7b39ef69.png">

**Comment by g-tejas** [comment]
I wasnt able to do it on code sandbox because it kept using nuxt 2 but, i have uploaded it on github,
https://github.com/g-tejas/highcharts-test
<img width="661" alt="Screenshot 2022-05-23 at 5 00 37 PM" src="https://user-images.githubusercontent.com/76802638/169783568-ee0ae934-500f-4bd2-bef9-59d6f12a361d.png">
<highchart> works perfectly, but highstock doesn't. im not sure what im doing wrong, thanks for helping out

**Comment by richardeschloss** [comment]
> Thank you!! I have a small problem, whenever I install nuxt-highcharts@3.0.4, its installing highcharts 10.1.0 instead of 10.0.0. Should i just manually specify it in package.json and yarn install it? Also whats the difference. between rc3 and the one shown below (i cloned your branch) <img alt="Screenshot 2022-05-23 at 4 18 51 PM" width="420" src="https://user-images.githubusercontent.com/76802638/169775519-4d5ff983-a20d-4df4-8dff-082c7b39ef69.png">

Hi, I just pushed 3.0.5. which should clamp the highcharts version to 10.0.0 (there appears to be some bug in the future version with `setTicks` which causes issues). You can also manually install that version with "npm i highcharts@10.0.0" . 

The version of Nuxt being tested against is:
https://github.com/richardeschloss/nuxt-highcharts/blob/c23660525c7a8fb796d6618c012055bc57b0f802/package.json#L41

Which will resolve to whatever the latest "release candidate for Nuxt3" is. So that specific version can change many times a day (and it's possible that those changes can break existing code).

**Comment by richardeschloss** [comment]
> I wasnt able to do it on code sandbox because it kept using nuxt 2 but, i have uploaded it on github, https://github.com/g-tejas/highcharts-test <img alt="Screenshot 2022-05-23 at 5 00 37 PM" width="661" src="https://user-images.githubusercontent.com/76802638/169783568-ee0ae934-500f-4bd2-bef9-59d6f12a361d.png"> works perfectly, but highstock doesn't. im not sure what im doing wrong, thanks for helping out

I'm glad to see progress being made! I believe highstock isn't working because that chart expects data to be formatted a certain way (in "ohlc" format):

```js
  data: [ 
    [ epochTime, open, high, low, close ],
    [ epochTime, open, high, low, close ] 
  ]  
```

Having `[1,2,3]` would not work because it's invalid stock chart data. 


https://github.com/richardeschloss/nuxt-highcharts/blob/d17c2cf6a1453a15a46a0f392ab29ab35a021bd9/components/charts/StockChart.vue#L39

**Comment by g-tejas** [comment]
![Screenshot 2022-05-24 at 1 56 56 AM](https://user-images.githubusercontent.com/76802638/169879134-8f93dde8-ee62-479d-8fe3-9642e01c2768.png)

Still have no luck sir, I copied the exact code over, but i still get the same cannot read properties of undefined error. Furthermore, this [codesandbox](https://codesandbox.io/s/highcharts-stockgui-tools-see-whats-happen-with-large-toolbar-20pbm?file=/src/components/Chart.vue) was able to plot stock chart with just 1,2, 3 . To replicate this issue, I ran "npx nuxi init test" to create a freshinstall of nuxt project, installed the latest nuxt-highcharts version as u stated. Added the module into the nuxt config. Copied the ohlcv json + Stock chart vue file into my app.vue. Could this be a typescript issue?

**Comment by richardeschloss** [comment]
Locally, clone this repo, switch to the working branch (feat/v3-rc) and run "npm run dev" and select the stock chart from the app. It will work..

My guess is you may need to uninstall highcharts and re-install the version 10.0.0.

**Comment by g-tejas** [comment]
Yes, ive checked the highcharts version, its 10.0.0. Also i can clone and it works, but I still want to add this plugin to my existing project, which i already have the code for, so i would need to do it via the yarn add method instead of just cloning.

Thanks for the help anyway

**Comment by richardeschloss** [comment]
In another local project, it should still work with npm install and yarn add. I can test on my end too

**Comment by g-tejas** [comment]
Unfortunately i wasnt able to, (from a fresh new nuxt project).

**Comment by richardeschloss** [comment]
Ok, I can repro this on my end, I re-opened the issue and will investigate.

**Comment by richardeschloss** [comment]
Ok, the feature in #43 seems to responsible for partially breaking things. Importing indicators seems to depend on existing global variables to be defined, so I'll figure out the better place to put that code. In the meantime, a non-ideal workaround is to comment out the indicators and it will work.

Comment out:
https://github.com/richardeschloss/nuxt-highcharts/blob/14dba971c48730f8947bc987edce64e77f2f291f/lib/components.js#L34

and
https://github.com/richardeschloss/nuxt-highcharts/blob/14dba971c48730f8947bc987edce64e77f2f291f/lib/components.js#L36

A better solution should be coming eventually

**Comment by richardeschloss** [comment]
Ok, I was able to fix it on my end. I release 3.0.6 with what seems to be working code now.  Tested against 10.0.0 . (it's on the roadmap to support highcharts lts)

**Comment by g-tejas** [comment]
Thank you, it works now! Really appreciate all the help and quick responses!
